OPENAI_API_KEY="sk-Yz5JjcWUF_325vb4N4aSNMOmAkRFTu3WHm6R-g7pXVT3BlbkFJ_fdetsWXcXdmDXZ8FZfvxoynEN-NOsYUmHknz9JwkA"
SERPER_API_KEY="5cbe6ac71fee0a4d725a0a12a80663b0fcaa28bd"
# YOUTUBE_API_KEY=AIzaSyDahQ_IDFXmVgleh065_UeHHro5sddImiM
YOUTUBE_API_KEY="AIzaSyD-ukVB19zkPmTSxK-VvO8culcHotD2I5U"
FIRECRAWL_API_KEY="fc-970a8239bdf54a36a23f62bbaa447313"
GROQ_API_KEY="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"
INSTAGRAM_USERNAME="the_smart_funnel"
INSTAGRAM_PASSWORD="Firescan2024+"
DEEPGRAM_API_KEY="46d16104048c4bd6b223b69c7bc05b2a3df4de75" 
Answer = "dydy123+"