[tool.poetry]
name = "latest_ai_development"
version = "0.1.0"
description = "latest-ai-development using crewAI"
authors = ["Your Name <you@example.com>"]
packages = [
    { include = "smartfunnel", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.10,<=3.13"
crewai = { extras = ["tools"], version = ">=0.70.1,<1.0.0" }
python-dotenv = "1.0.0"
firecrawl-py = "^0.0.20"
embedchain = {extras = ["youtube"], version = "^0.1.116"}
langchain-anthropic = "^0.1.20"
ollama = "^0.2.1"

[tool.poetry.scripts]
smartfunnel = "smartfunnel.main:run"
run_crew = "smartfunnel.main:run"
train = "smartfunnel.main:train"
replay = "smartfunnel.main:replay"
test = "smartfunnel.main:test"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
useLibraryCodeForTypes = true
exclude = [".cache"]

[tool.ruff]
# https://beta.ruff.rs/docs/configuration/
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']